### ISSUE TITLE
Can't add item with invalid item grant

### ISSUE THREAD

**Issue by mhilbrunner** [kristianserrano/swade-item-tables-issue-tracker#16]
Turns out I had a item (an edge) that had an item link with a broken reference/link/UUID, so it shows up as a red in the item sheet.
A player tried to add that edge for a advance, which silently added the item to the character without generating a advance.
This error occurs in the console:

```js
 TypeError: Cannot read properties of null (reading 'handleChoices')
[Detected 2 packages: system:swade(4.1.1), swade-item-tables(1.21.9)]
    at SwadeItem.getItemGrantChain (SwadeItem.ts:640:39)
    at async SwadeItem.grantEmbedded (SwadeItem.ts:582:24)
    at async SwadeItem._onCreateOperation (SwadeItem.ts:880:11)
    at async #handleCreateDocuments (foundry-esm.js:56450:7)
    at async SwadeItem.createDocuments (foundry-esm.js:11423:23)
    at async CharacterBuilder._onDropAdvanceItem (CharacterBuilder.mjs:1262:38)
```

Either the item shouldn't be added or a advance should still be generated (probably the latter). In either case, IMO an error/warning should be shown.

**Comment by kristianserrano** [comment]
That looks like it's actually a bug in the SWADE system. SwadeItem is a class from the system itself.

**Comment by kristianserrano** [comment]
Was this ever resolved in the SWADE system itself?

**Comment by mhilbrunner** [comment]
I forgot about this! I haven't found time to test as its a pretty arcane (and easily fixed) issue, but looking at the code, I'd assume this was fixed a week ago by https://gitlab.com/peginc/swade/-/merge_requests/768, which adds a null check to this exact code path. Closing!
